Dead letter exchange
letsdeel/rabbitmq pull request #2
Opened 2021-09-03 18:15 UTC by felix-zg

2021-09-03 18:16 UTC, felix-zg commented
![image](https://user-images.githubusercontent.com/19651417/132049798-a2876866-d639-45ac-8af9-bd450ae15378.png)

2021-09-09 08:35 UTC, gilad-deel requested changes

2021-09-09 08:35 UTC, gilad-deel commented on index.js
> +                    await this.channel.publish('', DLQ_NAME, Buffer.from(JSON.stringify(msg)));
replace content with `content.toString('utf8')`

2021-09-09 08:35 UTC, gilad-deel commented on index.js
> +                            await this.channel.assertExchange(this.exchange, 'x-delayed-message', {arguments: {'x-delayed-type': 'direct'}});
make this first in block

2021-09-09 08:35 UTC, gilad-deel commented on index.js
> +            });
1 line

2021-09-09 09:08 UTC, felix-zg commented
`{"fields":{"consumerTag":"amq.ctag-SwkySIO4h8gcVqWVPMsv8w","deliveryTag":501,"redelivered":false,"exchange":"/f","routingKey":"/f"},"properties":{"headers":{"x-death":[{"count":5,"exchange":"/f_RetryExchange","queue":"/f_RetryQueue","reason":"expired","routing-keys":["/f"],"time":{"!":"timestamp","value":1631177824}},{"count":5,"exchange":"/f","queue":"/f","reason":"rejected","routing-keys":["/f"],"time":{"!":"timestamp","value":1631177819}}],"x-first-death-exchange":"/f","x-first-death-queue":"/f","x-first-death-reason":"rejected"}},"content":"\"{\\\"test\\\":0}\""}
`

2021-09-09 10:18 UTC, gilad-deel approved these changes

2021-09-09 10:19 UTC, gilad-deel approved these changes

2021-09-09 10:19 UTC, merged